phases:
- phase: Windows
  queue:
    timeoutInMinutes: 90
  steps:
    - script: build\CIBuild.cmd -configuration $(_configuration) -prepareMachine $(_additionalArgs)
    - task: PublishBuildArtifacts@1
      displayName: publish artifacts on failure
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\$(_configuration)'
        ArtifactName: '$(_configuration) artifacts'
        publishLocation: Container
      continueOnError: true
      condition: failed()
    - task: PublishTestResults@2
      displayName: upload XML test results
      inputs:
        testRunner: 'xUnit'
        testResultsFiles: '**/*.xml' 
        searchFolder: '$(Build.SourcesDirectory)\artifacts\$(_configuration)\TestResults'
        configuration: '$(_configuration)'
        publishRunAttachments: true
      continueOnError: true
      condition: always()